package com.oceanview.controller;

import com.oceanview.dao.ReservationDAO;
import com.oceanview.model.Reservation;
import com.oceanview.model.User;

import java.io.IOException;
import java.text.SimpleDateFormat;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

@WebServlet("/PrintBillPdf")
public class PrintBillPdfServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        // ✅ Session check
        HttpSession session = request.getSession(false);
        User loggedUser = (session != null) ? (User) session.getAttribute("loggedUser") : null;

        if (loggedUser == null) {
            response.sendRedirect(request.getContextPath() + "/login.jsp");
            return;
        }

        String resNo = request.getParameter("resNo");
        if (resNo == null || resNo.trim().isEmpty()) {
            response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Reservation number is required");
            return;
        }

        ReservationDAO dao = new ReservationDAO();
        Reservation r = dao.getReservationByNumber(resNo.trim());

        if (r == null) {
            response.sendError(HttpServletResponse.SC_NOT_FOUND, "Reservation not found");
            return;
        }

        // ✅ Role-based access
        String role = (loggedUser.getRole() == null) ? "" : loggedUser.getRole().toUpperCase();

        // USER can print only own bill
        if ("USER".equals(role)) {
            if (r.getUserId() == null || r.getUserId() != loggedUser.getId()) {
                response.sendError(HttpServletResponse.SC_FORBIDDEN, "You can print only your own bills");
                return;
            }
        }

        // ADMIN/STAFF can print all (no extra check)

        // ✅ PDF response headers
        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "inline; filename=\"Bill_" + r.getReservationNumber() + ".pdf\"");

        // ✅ Build PDF
        try (PDDocument doc = new PDDocument()) {

            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {

                float margin = 50;
                float y = 770;
                float leading = 18;

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                // Title
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_BOLD, 20);
                cs.newLineAtOffset(margin, y);
                cs.showText("Ocean View Resort - Bill / Invoice");
                cs.endText();

                y -= 35;

                // Sub info
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA, 12);
                cs.newLineAtOffset(margin, y);
                cs.showText("Reservation No: " + safe(r.getReservationNumber()));
                cs.endText();

                y -= leading;

                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA, 12);
                cs.newLineAtOffset(margin, y);
                cs.showText("Generated By: " + safe(loggedUser.getUsername()) + " (" + safe(role) + ")");
                cs.endText();

                y -= 30;

                // Customer block
                y = drawLine(cs, margin, y, 545);
                y -= 15;

                y = writeRow(cs, margin, y, "Guest Name", safe(r.getGuestName()));
                y = writeRow(cs, margin, y, "Contact", safe(r.getContactNumber()));
                y = writeRow(cs, margin, y, "Address", safe(r.getAddress()));
                y -= 10;

                // Reservation block
                y = drawLine(cs, margin, y, 545);
                y -= 15;

                y = writeRow(cs, margin, y, "Room Type", safe(r.getRoomType()));
                y = writeRow(cs, margin, y, "Check-in", r.getCheckIn() != null ? sdf.format(r.getCheckIn()) : "-");
                y = writeRow(cs, margin, y, "Check-out", r.getCheckOut() != null ? sdf.format(r.getCheckOut()) : "-");

                y -= 10;
                y = drawLine(cs, margin, y, 545);
                y -= 20;

                // Total
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_BOLD, 16);
                cs.newLineAtOffset(margin, y);
                cs.showText("Total Amount: Rs. " + r.getTotalAmount());
                cs.endText();

                y -= 40;

                // Footer
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_OBLIQUE, 10);
                cs.newLineAtOffset(margin, y);
                cs.showText("Thank you for choosing Ocean View Resort!");
                cs.endText();
            }

            doc.save(response.getOutputStream());
        }
    }

    private static String safe(String s) {
        if (s == null) return "";
        // PDFBox default fonts are limited; keep it simple
        return s.replace("\n", " ").replace("\r", " ");
    }

    private static float writeRow(PDPageContentStream cs, float x, float y, String label, String value) throws IOException {
        cs.beginText();
        cs.setFont(PDType1Font.HELVETICA_BOLD, 12);
        cs.newLineAtOffset(x, y);
        cs.showText(label + ": ");
        cs.endText();

        cs.beginText();
        cs.setFont(PDType1Font.HELVETICA, 12);
        cs.newLineAtOffset(x + 130, y);
        cs.showText(value);
        cs.endText();

        return y - 18;
    }

    private static float drawLine(PDPageContentStream cs, float x, float y, float width) throws IOException {
        cs.moveTo(x, y);
        cs.lineTo(x + width, y);
        cs.stroke();
        return y;
    }
}